language: python
python:
  - "3.5"

postgres:
  adapter: postgresql
  database: yummydb_test
  username: postgres
  
install:
  - pip install -r requirements.txt

before_script:
  - "psql -c 'createuser yummyadmin;' -P -d"
  - "psql -c 'createdb yummydb_test;' -U yummyadmin -h localhost"
  - "rake db:migrate"
  
script:
  - nosetests --exe -v
  - nosetests --exe --with-coverage --cover-package=app
  - coveralls

after_sucess:
  - "coveralls"
